feat(cli)!: remove default chain ID, endpoint URL (#1792)
## Summary
Removes the default RPC URL and chain IDs the CLI.

## Background
It is a safety issue to interact with the wrong chain, and so these
defaults should not be enshrined in the app.

## Changes
- Remove the default value from all `--sequencer.chain-id` arguments.
- Remove the default value from all `--sequencer-url` arguments.

## Testing
All smoke tests already explicitly provided chain ID and RPC URL and
thus keep working.

Ran manually: omitting either arguments now results in errors like this:

```
error: the following required arguments were not provided:
  --sequencer-url <SEQUENCER_URL>
```

## Changelogs
"Changelogs updated."

## Breaking Changelist
- All invocations of the CLI for interacting with Astria network
`astria-dusk-10` at `"https://rpc.sequencer.dusk-10.devnet.astria.org"`
no longer work. Chain ID and RPC URL now need to be set explicitly by
providing an environment variable or command line argumient.

Invocations that already had the chain ID and RPC URL present continue
working unchanged.