fix(charts): only use one of annotation and spec for ingress (#955)
## Summary
Update to only use either the annotation of the spec definition of
ingress class name.

## Background
Dev encountered this error while deploying charts:
```
Error: INSTALLATION FAILED: 2 errors occurred:
        * Ingress.extensions "node0-sequencer-grpc-ingress" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
        * Ingress.extensions "node0-sequencer-rpc-ingress" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
```
## Testing
Smoke test