fix: update `ring` dependency and update audit ignore list (#2021)
## Summary
Fixes for two new `cargo audit` warnings.

## Background
We get two warnings when running `cargo audit`, both for
[RUSTSEC-2025-0009](https://rustsec.org/advisories/RUSTSEC-2025-0009).
One is for `ring@0.16.20` and the other `ring@0.17.11`.

<details><summary>cargo audit output</summary><p>

```
Crate:     ring
Version:   0.16.20
Title:     Some AES functions may panic when overflow checking is enabled.
Date:      2025-03-06
ID:        RUSTSEC-2025-0009
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0009
Solution:  Upgrade to >=0.17.12
Dependency tree:
ring 0.16.20
└── jsonwebtoken 8.3.0
    └── ethers-providers 2.0.14
        ├── ethers-middleware 2.0.14
        │   └── ethers 2.0.14
        │       ├── astria-test-utils 0.1.0
        │       │   └── astria-composer 1.0.0
        │       ├── astria-composer 1.0.0
        │       ├── astria-cli 0.5.1
        │       ├── astria-bridge-withdrawer 1.0.1
        │       └── astria-bridge-contracts 0.1.0
        │           ├── astria-cli 0.5.1
        │           └── astria-bridge-withdrawer 1.0.1
        ├── ethers-contract 2.0.14
        │   ├── ethers-middleware 2.0.14
        │   └── ethers 2.0.14
        └── ethers 2.0.14

Crate:     ring
Version:   0.17.11
Title:     Some AES functions may panic when overflow checking is enabled.
Date:      2025-03-06
ID:        RUSTSEC-2025-0009
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0009
Solution:  Upgrade to >=0.17.12
Dependency tree:
ring 0.17.11
├── sct 0.7.1
│   └── rustls 0.21.12
│       ├── tungstenite 0.20.1
│       │   ├── tokio-tungstenite 0.20.1
│       │   │   └── ethers-providers 2.0.14
│       │   │       ├── ethers-middleware 2.0.14
│       │   │       │   └── ethers 2.0.14
│       │   │       │       ├── astria-test-utils 0.1.0
│       │   │       │       │   └── astria-composer 1.0.0
│       │   │       │       ├── astria-composer 1.0.0
│       │   │       │       ├── astria-cli 0.5.1
│       │   │       │       ├── astria-bridge-withdrawer 1.0.1
│       │   │       │       └── astria-bridge-contracts 0.1.0
│       │   │       │           ├── astria-cli 0.5.1
│       │   │       │           └── astria-bridge-withdrawer 1.0.1
│       │   │       ├── ethers-contract 2.0.14
│       │   │       │   ├── ethers-middleware 2.0.14
│       │   │       │   └── ethers 2.0.14
│       │   │       └── ethers 2.0.14
│       │   └── async-tungstenite 0.23.0
│       │       └── tendermint-rpc 0.34.1
│       │           ├── astria-sequencer-relayer 1.0.0
│       │           ├── astria-sequencer-client 0.1.0
│       │           │   ├── astria-sequencer-relayer 1.0.0
│       │           │   ├── astria-conductor 1.0.0
│       │           │   ├── astria-composer 1.0.0
│       │           │   ├── astria-cli 0.5.1
│       │           │   ├── astria-bridge-withdrawer 1.0.1
│       │           │   └── astria-auctioneer 0.0.1
│       │           ├── astria-conductor 1.0.0
│       │           ├── astria-composer 1.0.0
│       │           └── astria-bridge-withdrawer 1.0.1
│       ├── tonic 0.10.2
│       │   ├── tonic-health 0.10.2
│       │   │   └── astria-composer 1.0.0
│       │   ├── penumbra-tower-trace 0.80.10
│       │   │   └── astria-sequencer 1.0.0
│       │   ├── penumbra-sct 0.80.10
│       │   │   └── penumbra-ibc 0.80.10
│       │   │       ├── astria-sequencer-utils 0.1.0
│       │   │       ├── astria-sequencer 1.0.0
│       │   │       └── astria-core 0.1.0
│       │   │           ├── astria-sequencer-utils 0.1.0
│       │   │           ├── astria-sequencer-relayer 1.0.0
│       │   │           ├── astria-sequencer-client 0.1.0
│       │   │           ├── astria-sequencer 1.0.0
│       │   │           ├── astria-core 0.1.0
│       │   │           ├── astria-conductor 1.0.0
│       │   │           ├── astria-composer 1.0.0
│       │   │           ├── astria-cli 0.5.1
│       │   │           ├── astria-bridge-withdrawer 1.0.1
│       │   │           ├── astria-bridge-contracts 0.1.0
│       │   │           └── astria-auctioneer 0.0.1
│       │   ├── penumbra-proto 0.80.10
│       │   │   ├── penumbra-txhash 0.80.10
│       │   │   │   └── penumbra-ibc 0.80.10
│       │   │   ├── penumbra-tct 0.80.10
│       │   │   │   ├── penumbra-txhash 0.80.10
│       │   │   │   ├── penumbra-sct 0.80.10
│       │   │   │   └── penumbra-keys 0.80.10
│       │   │   │       └── penumbra-sct 0.80.10
│       │   │   ├── penumbra-sct 0.80.10
│       │   │   ├── penumbra-num 0.80.10
│       │   │   │   ├── penumbra-ibc 0.80.10
│       │   │   │   └── penumbra-asset 0.80.10
│       │   │   │       ├── penumbra-keys 0.80.10
│       │   │   │       └── penumbra-ibc 0.80.10
│       │   │   ├── penumbra-keys 0.80.10
│       │   │   ├── penumbra-ibc 0.80.10
│       │   │   ├── penumbra-asset 0.80.10
│       │   │   ├── astria-sequencer 1.0.0
│       │   │   └── astria-core 0.1.0
│       │   ├── penumbra-ibc 0.80.10
│       │   ├── ibc-proto 0.41.0
│       │   │   ├── penumbra-proto 0.80.10
│       │   │   ├── penumbra-ibc 0.80.10
│       │   │   ├── ibc-types-lightclients-tendermint 0.12.1
│       │   │   │   └── ibc-types 0.12.1
│       │   │   │       ├── penumbra-proto 0.80.10
│       │   │   │       ├── penumbra-ibc 0.80.10
│       │   │   │       ├── cnidarium 0.80.10
│       │   │   │       │   ├── penumbra-sct 0.80.10
│       │   │   │       │   ├── penumbra-proto 0.80.10
│       │   │   │       │   ├── penumbra-ibc 0.80.10
│       │   │   │       │   ├── cnidarium-component 0.80.10
│       │   │   │       │   │   └── penumbra-sct 0.80.10
│       │   │   │       │   └── astria-sequencer 1.0.0
│       │   │   │       ├── astria-sequencer 1.0.0
│       │   │   │       ├── astria-core 0.1.0
│       │   │   │       ├── astria-cli 0.5.1
│       │   │   │       ├── astria-bridge-withdrawer 1.0.1
│       │   │   │       └── astria-bridge-contracts 0.1.0
│       │   │   ├── ibc-types-core-connection 0.12.1
│       │   │   │   ├── ibc-types-path 0.12.1
│       │   │   │   │   └── ibc-types 0.12.1
│       │   │   │   ├── ibc-types-lightclients-tendermint 0.12.1
│       │   │   │   ├── ibc-types-core-channel 0.12.1
│       │   │   │   │   ├── ibc-types-path 0.12.1
│       │   │   │   │   └── ibc-types 0.12.1
│       │   │   │   └── ibc-types 0.12.1
│       │   │   ├── ibc-types-core-commitment 0.12.1
│       │   │   │   ├── ibc-types-lightclients-tendermint 0.12.1
│       │   │   │   ├── ibc-types-core-connection 0.12.1
│       │   │   │   ├── ibc-types-core-channel 0.12.1
│       │   │   │   └── ibc-types 0.12.1
│       │   │   ├── ibc-types-core-client 0.12.1
│       │   │   │   ├── ibc-types-path 0.12.1
│       │   │   │   ├── ibc-types-lightclients-tendermint 0.12.1
│       │   │   │   ├── ibc-types-core-connection 0.12.1
│       │   │   │   ├── ibc-types-core-channel 0.12.1
│       │   │   │   └── ibc-types 0.12.1
│       │   │   ├── ibc-types-core-channel 0.12.1
│       │   │   └── astria-sequencer 1.0.0
│       │   ├── astria-sequencer-relayer 1.0.0
│       │   ├── astria-sequencer 1.0.0
│       │   ├── astria-grpc-mock-test 0.1.0
│       │   ├── astria-grpc-mock 0.1.0
│       │   │   ├── astria-sequencer-relayer 1.0.0
│       │   │   ├── astria-grpc-mock-test 0.1.0
│       │   │   ├── astria-conductor 1.0.0
│       │   │   ├── astria-composer 1.0.0
│       │   │   └── astria-bridge-withdrawer 1.0.1
│       │   ├── astria-core 0.1.0
│       │   ├── astria-conductor 1.0.0
│       │   ├── astria-composer 1.0.0
│       │   ├── astria-bridge-withdrawer 1.0.1
│       │   └── astria-auctioneer 0.0.1
│       ├── tokio-rustls 0.24.1
│       │   ├── tonic 0.10.2
│       │   ├── reqwest 0.11.27
│       │   │   ├── tendermint-rpc 0.34.1
│       │   │   ├── ethers-providers 2.0.14
│       │   │   ├── ethers-middleware 2.0.14
│       │   │   ├── astria-composer 1.0.0
│       │   │   └── astria-bridge-withdrawer 1.0.1
│       │   ├── jsonrpsee-client-transport 0.20.4
│       │   │   └── jsonrpsee-ws-client 0.20.4
│       │   │       └── jsonrpsee 0.20.4
│       │   │           ├── celestia-rpc 0.1.1
│       │   │           │   └── astria-conductor 1.0.0
│       │   │           ├── astria-test-utils 0.1.0
│       │   │           └── astria-conductor 1.0.0
│       │   ├── hyper-rustls 0.24.2
│       │   │   ├── reqwest 0.11.27
│       │   │   └── jsonrpsee-http-client 0.20.4
│       │   │       └── jsonrpsee 0.20.4
│       │   └── async-tungstenite 0.23.0
│       ├── reqwest 0.11.27
│       └── hyper-rustls 0.24.2
├── rustls-webpki 0.101.7
│   └── rustls 0.21.12
└── rustls 0.21.12

error: 2 vulnerabilities found!
```

</p></details>

One of these vulnerabilities can be resolved simply by running `cargo
update ring@0.17.11`. However, to resolve the one caused by
`ring@0.16.20`, we need to change our own usage of `ethers` to `alloy`
throughout.

For now, this is worked around by adding an entry to the ignore list.
The outstanding work is being tracked at #2020.

## Changes
- Ran `cargo update ring@0.17.11`
- Ignore RustSec warning in `.cargo/audit.toml`.

## Testing
Ran `cargo audit` locally.

## Changelogs
No updates required - nothing really fixed or updated.

## Related Issues
Closes #2018.
Closes #2019.